### ISSUE TITLE
Suggestion: Prevent `ADD` action if the custom-id already exists.

### ISSUE THREAD

**Issue by jgjgill** [toss/overlay-kit#46]
## Problem situation

When specifying `custom-id` separately on `overlay.open`, multiple occurrences of that event will result in an error.

**Example code**

```tsx
<button
  onClick={() => {
    overlay.open(
      ({ isOpen, close, unmount }) => {
        return (
          <CenterModal isOpen={isOpen} onExit={unmount}>
            <div>
              <p>MODAL CONTENT</p>
              <button onClick={close}>close modal</button>
            </div>
          </CenterModal>
        );
      },
      { overlayId: 'overlayid-1' }
    );
  }}
>
  open center modal
</button>
```

**Demo**

https://github.com/toss/overlay-kit/assets/79239852/d4dea1ae-a85e-4370-bcc0-398943da2588

## Cause of the problem

This appears to be caused by the same `overlayId` already existing in the `overlayOrderList`.

## Workaround

I thought of adding the following code in the `ADD` action.
If the `overlayId` already exists, return the existing `state`.

**reducer.ts**

```ts
    case 'ADD': {
      if (state.overlayOrderList.includes(action.overlay.id)) {
        return state;
      }

      return {
        current: action.overlay.id,
        overlayOrderList: [...state.overlayOrderList, action.overlay.id],
        overlayData: {
          ...state.overlayData,
          [action.overlay.id]: action.overlay,
        },
      };
    }
```

**Expected behavior**

https://github.com/toss/overlay-kit/assets/79239852/e2657958-cac3-43fa-b429-1dfb027ca83f

If you think the suggestion is appropriate, would you mind if I add a feature fix and test code? 🧐

**Comment by ojj1123** [comment]
This issue occurs even if not calling `overlay.open` quickly.

![스크린샷 2024-07-11 22 33 40](https://github.com/toss/overlay-kit/assets/33178048/f94e51da-68f0-4b59-b422-16f51f64fe6f)

As @jgjgill said, that is because every calling `overlay.open`, `ADD` action is triggered and then the same overlay key is added to `overlayState.overlayOrderList`.

https://github.com/toss/overlay-kit/blob/090e68f81b347bb3509842b30fc0bd4ab015f2dd/packages/src/context/reducer.ts#L16

**Comment by jungpaeng** [comment]
I understand why this issue is occurring.

Since `overlayId` functions as a `key` in React, it should only exist once on a screen.
Therefore, some action is needed when the same custom ID is opened multiple times with `overlay.open`.

While returning the state as-is when `overlayId` already exists, as shown in your code, can prevent errors, it might appear as a bug to the user. From the user’s perspective, it seems like the overlay isn’t opening even though they attempted to open it.

So, I think it would be better to throw an error to make it clear that this is not the correct usage. Additionally, we should update the documentation to inform users not to open the same custom ID multiple times.

What do you think?

**Comment by ojj1123** [comment]
> From the user’s perspective, it seems like the overlay isn’t opening even though they attempted to open it

Yeah, I agree with you. If returning the as-is state with the same overlay key, it could be possible. 🤔

> So, I think it would be better to throw an error to make it clear that this is not the correct usage. Additionally, we should update the documentation to inform users not to open the same custom ID multiple times.

Btw, this warning occurs when below senario:
1. calling `overlay.open()` with custom id
2. close the overlay
3. again open with custom id
4. close it
5. ...

I think this case would be correct. As a video in [my comment above](https://github.com/toss/overlay-kit/issues/46#issuecomment-2222991645), it shows the general case.
That warning occurs because when triggering `ADD` action with custom id, that key is added to `overlayOrderList` even if it is already in `overlayOrderList`. So I think we need to prevent it from being added to `overlayOrderList` if there is the same key.

How about this workaround? 

```ts
    case 'ADD': {
      const isExisted = state.overlayOrderList.includes(action.overlay.id);

      return {
        current: action.overlay.id,
        overlayOrderList: isExisted ? state.overlayOrderList : [...state.overlayOrderList, action.overlay.id],
        overlayData: {
          ...state.overlayData,
          [action.overlay.id]: action.overlay,
        },
      };
    }
```

**Comment by jgjgill** [comment]
@jungpaeng 

Oh, I didn't think about the user and focused on eliminating errors. 😂
Throwing an error is certainly appropriate in this situation, both for the user and the library.
I also agree that this is not the correct usage. 🧐

So maybe the code would look something like this?

**reducer.ts**

```ts
    case 'ADD': {
      if (state.overlayOrderList.includes(action.overlay.id)) {
        throw new Error('The same overlayId exists.');
      }
    ...
```

**Expected behavior**

https://github.com/user-attachments/assets/5a3aa6bf-40c3-4fe7-b393-1a18c4b41c28

**Comment by ojj1123** [comment]
Yeah I think "open and open repeatly" is not the intended use case.
But I'm wondering **open -> close w/o unmount -> again open** is also wrong. If this library throws the error for opening a overlay with the same key, it throws the error on the use case I said.

**Comment by jgjgill** [comment]
> Additionally, I assumed that executing close without unmount means the user is aware of this and intentionally keeps the overlay in memory.

This seems to be an example of [that comment](https://github.com/toss/overlay-kit/issues/44#issuecomment-2220294751). I think it's right to throw the error.

**Comment by jungpaeng** [comment]
I'm outside right now, so I can't write in detail, but I wanted to leave a brief note. Thank you very much for your interest and for proposing a solution.

First, we need to prevent opening an overlay without closing it first. In this case, it seems appropriate to return an error.

However, reopening an overlay without unmounting it after closing should work. There are cases where not unmounting intentionally is done for performance optimization reasons.

Therefore, in the ADD phase of the reducer, we need to check if the overlay currently exists in overlayData and refer to the value of isOpen to make appropriate modifications.

I'll revisit this issue later. Thank you once again.

**Comment by jgjgill** [comment]
> Therefore, in the ADD phase of the reducer, we need to check if the overlay currently exists in overlayData and refer to the value of isOpen to make appropriate modifications.

Ah, I understand. I was misunderstanding the problem situation 😂.
Thanks for the quick feedback.

**Comment by jungpaeng** [comment]
@ojj1123 @jgjgill Hello. I have written PR #53 based on the feedback from both of you.

Could you please review it before I finalize it, if you have time?
