### ISSUE TITLE
Components inside overlay.open do not react properly to external state

### ISSUE THREAD

**Issue by XionWCFM** [toss/overlay-kit#66]
## Issue Description:

This problem occurred in overlay-kit 1.3.0 version.

I ran into the following problem while working with "overlay-kit".

Components inside the "overlay.open" do not react properly when the state exists externally

## Expected

```tsx
export default function Page() {
  const [notWorkingText, setNotWorkingText] = useState("world");
  return (
    <div>
      <button
        onClick={() => {
          overlay.open(({ isOpen }) => {
            return isOpen ? (
              <div>
                <div>{notWorkingText}</div>
                <button
                  onClick={() => {
                    setNotWorkingText("hello");
                  }}
                >
                  text change
                </button>
              </div>
            ) : null;
          });
        }}
      >
        not work example button
      </button>
  </div>
)
```

When I click the "Change Text" button, I think the text that appears on the screen should change from world to hello.

But this example doesn't actually work

Please let me know if I'm doing something wrong

## Case that works

```tsx
      <button
        onClick={() => {
          overlay.open(({ isOpen, close }) => {
            // eslint-disable-next-line react-hooks/rules-of-hooks
            const [workingText, setWorkingText] = useState("world");
            return (
              <div>
                <div>{workingText}</div>
                <button
                  onClick={() => {
                    setWorkingText("hello");
                  }}
                >
                  text change
                </button>
              </div>
            );
          });
        }}
      >
        work example
      </button>
```

This example works perfectly. I think it probably responds appropriately to state changes because it holds the state inside the component.

## Is this a bug?

If this isn't a bug, I'm curious how this use case can be handled.

## Additional Context

[I've posted a code snippet that reproduces this issue](https://github.com/XionWCFM/react-query-extend-example/blob/main/app/overlay/page.tsx)

Thank you for your efforts

**Comment by jungpaeng** [comment]
You’re correct in identifying the issue. This limitation is due to the nature of the library, and it’s not something that can be fixed easily. This problem has existed since the use-overlay in slash.

When the overlay opens, it captures a snapshot of its internal state, making it incompatible with dynamic children. Here are a few ways to work with dynamic content that come to mind:

1. Move the state inside the component, as you have shown in your example.
2. Manage the state directly without using overlay-kit.

This issue is also present in mantine’s modal manager, which offers a similar API.

Link: https://mantine.dev/x/modals/#dynamic-content-and-the-modals-manager

Thank you for your efforts.

**Comment by XionWCFM** [comment]
Thank you for your kindness. 

I've often encountered this problem in the past when writing code with patterns similar to overlay-kit.

Thanks to your explanation, I understand the problem better.

thank you!

**Comment by jungpaeng** [comment]
It seems your questions have been resolved, so I will close this issue for now.
If you have any further questions related to this, please feel free to reopen the issue!
