### ISSUE TITLE
Proposal to Modernize Testing Approach with @testing-library/user-event

### ISSUE THREAD

**Issue by XionWCFM** [toss/overlay-kit#68]
# Summery

I'd like to suggest migrating the current "overlay-kit"'s testing methods to use userEvent. Would you please consider it?

# Benefit

- By using userEvent, you will be able to write test code in a form that is more similar to the user's actual use cases.

- The more your tests resemble the way your software is used, the more confidence they can give you.

- All test cases currently used in "overlay-kit" can be migrated to userEvent without any problems.

# My Opinion

If this proposal seems like a necessary but tedious task, 

I am ready to work on it.

Could you please consider this suggestion?

Thank you always for your dedication.

**Comment by jungpaeng** [comment]
I have always thought that the current overlay-kit tests needed improvement, as they are not perfectly written, but I haven’t had the time to address this.

As you mentioned, using user-event to write the tests would make them more similar to actual user scenarios. I think it’s a good direction and have no reason to oppose it.

If you have the time, could you proceed with the work? There’s no need to push yourself too hard.

**Comment by XionWCFM** [comment]
Wow, now let's do the userEvent migration. 

And this is a bit of a different topic, but I think it would be nice to have more test cases for "overlay-kit"

What do you think about this?

**Comment by jungpaeng** [comment]
> I think it would be nice to have more test cases for "overlay-kit"

Absolutely, I agree with adding more test cases for the “overlay-kit.”

Expanding the test coverage is an excellent idea. It enhances the robustness and reliability of the codebase and helps catch potential issues early. By simulating more user interactions and edge cases, we can create a more polished and user-friendly product.

Additionally, more test cases serve as valuable documentation for new developers joining the project. They can quickly understand the expected behavior of various components and functionalities by looking at the tests.

I fully support this initiative and am ready to work together to identify and implement additional test scenarios. Please feel free to share any specific ideas or areas you think need more testing. Thank you for your dedication and commitment to improving our project.

**Comment by XionWCFM** [comment]
great! First, we will perform user event migration and then think about this issue.

thank you
